config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "boards#index"

  resources :users do
    resources :boards
  end

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user, optional: :true

  has_many :lists, dependent: :destroy

  def self.by_name
    order(:name)
  end

  def self.by_description
    order(:description)
  end

  def changedescription(d)
    self.update(description: d)
  end

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :boards, optional: :true
  has_many :tasks, dependent: :destroy

  def self.by_name
    order(:name)
  end

  def self.by_description
    order(:description)
  end

  def changedescription(d)
    self.update(description: d)
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list, optional: :true

  def self.by_name
    order(:name)
  end

  def self.by_priority
    order(:priority)
  end

  def changepriority(p)
    self.update(priority: p)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = current_user.boards
  end

  def show
    @lists = @board.lists
  end

  def new
    @board = current_user.boards.new
  end

  def create
    @board = current_user.boards.create(board_params)
    if@board.save
      flash[:success] = "Board Created"
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      flash[:success] = "Board Updated"
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    flash[:success] = "Board Deleted"
    redirect_to user_boards_path(current_user)
  end

  private
    def board_params
      params.require(:board).permit(:name, :description, :user_id)
    end

    def set_board
      @board = current_user.boards.find(params[:id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board, except: [:destroy]
  before_action :set_list, except: [:new, :create]

  def index
    @lists = @board.lists
    @tasks = @list.tasks
  end

  def show
  end

  def new
    @board = Board.find(params[:board_id])
    @list = @board.lists.new
  end

  def create
    @board = Board.find(params[:board_id])
    @list = @board.lists.create(list_params)
    if @list.save
      flash[:success] = "List Created"
      redirect_to @board
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      flash[:success] = "List Updated"
      redirect_to board_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    flash[:success] = "List Deleted"
    redirect_to user_boards_path(current_user)
  end

  private
    def set_board
      @board = current_user.boards.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :description, :board_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, except: [:index, :new, :create]

  def index
    @tasks = @list.tasks.by_priority
  end

  def show
  end

  def new
    @task = @list.tasks.new
  end

  def create
    @task = @list.tasks.create(task_params)
    if @task.save
      flash[:success] = "Task Created"
      redirect_to list_tasks_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task Updated"
      redirect_to list_tasks_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task Deleted"
    redirect_to list_tasks_path(@list)
  end

  private
  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :priority, :list_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.save
      redirect_to user_boards_path
    else
      render :edit
    end
  end

  private
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 <div class="field">
   <%= f.label :description %>
   <%= f.text_area :description, class: "input" %>
 </div>
 <%= f.submit nil, class: "ui green button" %>
<% end %>

app/views/boards/create.html.erb
<h1>Create Board</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/destroy.html.erb
<h1>Destroy Board</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/edit.html.erb
<h1 class="ui header">Edit Board</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/boards/index.html.erb
<h1 class="ui header">Boards</h1>
<%= link_to "New Board", new_user_board_path(current_user), class: "ui small green button" %>
<div class="ui divider"></div>
<table class="ui blue table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><h3><%= link_to board.name, board %></h3><%= board.description %></td>
        <td><%= link_to 'Edit', edit_board_path(board), class: "ui blue button" %></td>
        <td><%= link_to 'Delete', board, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h1 class="ui header">Add Board</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/boards/show.html.erb
<h1 class="ui header"><%= @board.name %></h1>
<%= link_to 'Edit Board', edit_board_path(@board), class: "ui small blue button" %>
<%= link_to "New List", new_board_list_path(@board), class: "ui small green button" %>
<div class="ui divider"></div>

<div class="ui three column grid">
  <% @lists.each do |list| %>
    <div class="column">
      <div class="ui fluid card">
        <div class="content">
          <div class="header"><%= list.name %></div>
          <div class="description"><%= list.description %></div>
        </div>
        <div class="content">
          <h4 class="ui sub header">Tasks</h4>
          <div class="event">
            <div class="content">
              <div class="summary">
                <% list.tasks.each do |task| %>
                  <div class="center aligned header">
                  <%= "#{task.name}" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="ui two buttons">
            <%= link_to 'Show Tasks', list_tasks_path(list), class: "ui teal button" %>
          </div>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
              <%= link_to 'Edit', edit_board_list_path(@board), class: "ui blue button" %>
              <%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/update.html.erb
<h1>Update Board</h1>
<p>Find me in app/views/boards/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <% if current_user %>
  <%= link_to "Trollo", root_path, class: "item" %>
   <div class="ui simple dropdown item">
    Boards
    <i class="dropdown icon"></i>
    <div class="menu">
      <%= link_to "Add Board", new_board_path, class: "item" %>
      <% current_user.boards.each do |board| %>
        <%= link_to board.name, board, class: "item" %>
      <% end %>
    </div>
  </div>
  <% else %>
  <% end %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="ui form">
<%= form_for [@board, @list] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 <div class="field">
   <%= f.label :description %>
   <%= f.text_area :description, class: "input" %>
 </div>
 <%= f.submit nil, class: "ui green button" %>
<% end %>
</div>

app/views/lists/create.html.erb
<h1>Create List</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Destroy List</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1 class="ui header">Edit List</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>List Index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1 class="ui header">Add List</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/lists/show.html.erb
<h1>Show List</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/lists/update.html.erb
<h1>Update List</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/tasks/_form.html.erb
<div class="ui form">
<%= form_for [@list, @task] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "input" %>
 </div>
  <div class="inline fields">
    <label for="priority">Select Task Priority: </label>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:priority, "1") %>
        <%= f.label(:priority_1, " Highest Priority") %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:priority, "2") %>
        <%= f.label(:priority_2, " High Priority") %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:priority, "3") %>
        <%= f.label(:priority_3, " Medium Priority") %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:priority, "4") %>
        <%= f.label(:priority_4, " Low Priority") %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:priority, "5") %>
        <%= f.label(:priority_5, " Lowest Priority") %>
      </div>
    </div>
 </div>
 <%= f.submit nil, class: "ui green button" %>
<% end %>
</div>

app/views/tasks/create.html.erb
<h1>Create Task</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Destroy Task</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1 class="ui header">Edit Task</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/tasks/index.html.erb
<h1 class="ui header"><%= @list.name %></h1>
<%= link_to "New Task", new_list_task_path(@list), class: "ui small green button" %>
<div class="ui divider"></div>

<div class="ui three column grid">
  <% @tasks.each do |task| %>
    <div class="column">
      <div class="ui fluid card">
        <div class="content">
          <div class="header"><%= task.name %></div>
          <div class="meta">Priority: <%= task.priority %></div>
        </div>
        <div class="content">
          <div class="description"><%= task.description %></div>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
              <%= link_to 'Edit', edit_list_task_path(@list, task), class: "ui blue button" %>
              <%= link_to 'Delete', list_task_path(@list, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1 class="ui header">Add Task</h1>
<div class="ui divider"></div>

<%= render "form" %>

app/views/tasks/show.html.erb
<h1 class="ui header"><%= @task.name %></h1>
<%= link_to 'Edit Task', edit_list_task_path(@task), class: "ui small blue button" %>
<div class="ui divider"></div>

<div class="ui three column grid">
    <div class="column">
      <div class="ui fluid card">
        <div class="content">
          <div class="header"><%= @task.name %></div>
          <div class="center aligned description">Priority: <%= @task.priority %></div>
          <div class="description"><%= @task.description %></div>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
              <%= link_to 'Edit', edit_list_task_path(@task), class: "ui blue button" %>
              <%= link_to 'Delete', list_task_path(@task), method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/tasks/update.html.erb
<h1>Update Task</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/edit.html.erb
<% redirect_to edit_user_registration_path %>

app/views/users/update.html.erb
<h1>Update User</h1>
<p>Find me in app/views/users/update.html.erb</p>